### PR TITLE
Automate AWS api

### PR DESCRIPTION
**Pull request by pomkos**
Connect to AWS bucket, retrieve filenames with optional save. Retrieve n random names. Retrieve top 16 names (top 5 smallest size, top 5 largest, and the median 6). 

Also some bug fixes related to algo1, 2. Limit variable to limit how many timestamps are returned from each algo.

### CODE REVIEW

**Review by pomkos — COMMENTED** [review]
Also reorganized files one more time, so now we have dev and prod pypi libraries. Prod has all algos. Dev just has some helper functions that are helpful in developing/debugging algos.

**Comment by chand1012** [comment]
> 
> 
> @chand1012 may be able to help with cicd for incrementing the version number. Not 100% sure what goes into that though.

CI/CD for publishing to PyPI will be done in the coming days on a different branch, version numbers are generally done manually but I can look into automating those as well.

**Review by chand1012 — APPROVED** [review]
Looks good, let me know if you need help with merging on command line.

**Comment by pomkos** [comment]
@chand1012 Is command line merging preferred over using the github webgui?

**Comment by chand1012** [comment]
> @chand1012 Is command line merging preferred over using the github webgui?

No, but GitHub says it cannot merge automatically nor can you resolve it in the web GUI (which is actually kind of strange, GitHub is usually really good about these kind of things).

**Comment by pomkos** [comment]
I successfully merged, but I can't push the merge. You may have to take this one!

```
Total 6 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 3 local objects.
remote: This repository moved. Please use the new location:
remote:   https://github.com/pillargg/twitch_chat_analysis.git
remote: error: GH006: Protected branch update failed for refs/heads/main.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/pomkos/twitch_chat_analysis
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/pomkos/twitch_chat_analysis'
```

**Pull request merged**
